package iti.jets.persistence.entities;// default package
// Generated 4 Mar 2024, 00:40:35 by Hibernate Tools 6.0.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * CartItem generated by hbm2java
 */
@Entity
@Table(name="cart_item"
    ,catalog="ecommercedb"
)
public class CartItem  implements java.io.Serializable {


     private int cartItemId;
     private Product product;
     private Cart cart;
     private Integer quantity;
     private Integer totalPrice;

    public CartItem() {
    }

	
    public CartItem(int cartItemId) {
        this.cartItemId = cartItemId;
    }
    public CartItem(int cartItemId, Product product, Cart cart, Integer quantity, Integer totalPrice) {
       this.cartItemId = cartItemId;
       this.product = product;
       this.cart = cart;
       this.quantity = quantity;
       this.totalPrice = totalPrice;
    }
   
     @Id 

    
    @Column(name="cart_item_id", unique=true, nullable=false)
    public int getCartItemId() {
        return this.cartItemId;
    }
    
    public void setCartItemId(int cartItemId) {
        this.cartItemId = cartItemId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cart_id")
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="total_price")
    public Integer getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }




}


