package iti.jets.persistence.entities;// default package
// Generated 4 Mar 2024, 00:40:35 by Hibernate Tools 6.0.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CreditCard generated by hbm2java
 */
@Entity
@Table(name="credit_card"
    ,catalog="ecommercedb"
)
public class CreditCard  implements java.io.Serializable {


     private int creditCardId;
     private String cardNumber;
     private Integer cvv;
     private Date expDate;
     private Set<Customer> customers = new HashSet<Customer>(0);

    public CreditCard() {
    }

	
    public CreditCard(int creditCardId) {
        this.creditCardId = creditCardId;
    }
    public CreditCard(int creditCardId, String cardNumber, Integer cvv, Date expDate, Set<Customer> customers) {
       this.creditCardId = creditCardId;
       this.cardNumber = cardNumber;
       this.cvv = cvv;
       this.expDate = expDate;
       this.customers = customers;
    }
   
     @Id 

    
    @Column(name="credit_card_id", unique=true, nullable=false)
    public int getCreditCardId() {
        return this.creditCardId;
    }
    
    public void setCreditCardId(int creditCardId) {
        this.creditCardId = creditCardId;
    }

    
    @Column(name="card_number", length=16)
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    
    @Column(name="cvv")
    public Integer getCvv() {
        return this.cvv;
    }
    
    public void setCvv(Integer cvv) {
        this.cvv = cvv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="exp_date", length=10)
    public Date getExpDate() {
        return this.expDate;
    }
    
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="creditCard")
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }




}


