package iti.jets.persistence.entities;// default package
// Generated 4 Mar 2024, 00:40:35 by Hibernate Tools 6.0.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerOrder generated by hbm2java
 */
@Entity
@Table(name="customer_order"
    ,catalog="ecommercedb"
)
public class CustomerOrder  implements java.io.Serializable {


     private int orderId;
     private Customer customer;
     private BigDecimal totalPrice;
     private Date date;
     private Set<BuyedItem> buyedItems = new HashSet<BuyedItem>(0);

    public CustomerOrder() {
    }

	
    public CustomerOrder(int orderId) {
        this.orderId = orderId;
    }
    public CustomerOrder(int orderId, Customer customer, BigDecimal totalPrice, Date date, Set<BuyedItem> buyedItems) {
       this.orderId = orderId;
       this.customer = customer;
       this.totalPrice = totalPrice;
       this.date = date;
       this.buyedItems = buyedItems;
    }
   
     @Id 

    
    @Column(name="order_id", unique=true, nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id")
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    
    @Column(name="total_price", precision=10, scale=2)
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerOrder")
    public Set<BuyedItem> getBuyedItems() {
        return this.buyedItems;
    }
    
    public void setBuyedItems(Set<BuyedItem> buyedItems) {
        this.buyedItems = buyedItems;
    }




}


