package iti.jets.persistence.entities;// default package
// Generated 4 Mar 2024, 00:40:35 by Hibernate Tools 6.0.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="ecommercedb"
)
public class Product  implements java.io.Serializable {


     private int productId;
     private String productName;
     private byte[] productImage;
     private BigDecimal price;
     private Integer stockCount;
     private Set<BuyedItem> buyedItems = new HashSet<BuyedItem>(0);
     private Set<CartItem> cartItems = new HashSet<CartItem>(0);

    public Product() {
    }

	
    public Product(int productId) {
        this.productId = productId;
    }
    public Product(int productId, String productName, byte[] productImage, BigDecimal price, Integer stockCount, Set<BuyedItem> buyedItems, Set<CartItem> cartItems) {
       this.productId = productId;
       this.productName = productName;
       this.productImage = productImage;
       this.price = price;
       this.stockCount = stockCount;
       this.buyedItems = buyedItems;
       this.cartItems = cartItems;
    }
   
     @Id 

    
    @Column(name="product_id", unique=true, nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

    
    @Column(name="product_name", length=255)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="product_image")
    public byte[] getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(byte[] productImage) {
        this.productImage = productImage;
    }

    
    @Column(name="price", precision=10, scale=2)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="stock_count")
    public Integer getStockCount() {
        return this.stockCount;
    }
    
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<BuyedItem> getBuyedItems() {
        return this.buyedItems;
    }
    
    public void setBuyedItems(Set<BuyedItem> buyedItems) {
        this.buyedItems = buyedItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<CartItem> getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set<CartItem> cartItems) {
        this.cartItems = cartItems;
    }




}


